<h1 style="font-size: 35px">
Chapter 1: Introduction
</h1>

One of the core concepts I want to brush up on is matrix multiplication, so here I will write a function to multiply matrices.

___

In [1]:
import numpy as np # to create arrays

In [2]:
def matrix_multiplication(A: np.array, B:np.array) -> np.array:
    # Check if the number of columns in A is equal to the number of rows in B
    if A.shape[1] != B.shape[0]:
        raise ValueError("A columns size must equal B rows size")
    
    # Initialize array
    product = np.zeros((A.shape[0],B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                product[i][j] += A[i][k] * B[k][j]

    return product

In [3]:
A = np.random.randint(0,10, size=(2,3))
B = np.random.randint(0,10, size=(3,2))
print(f"A: \n{A} \nB: \n{B}")

A: 
[[3 4 3]
 [6 5 2]] 
B: 
[[0 7]
 [0 5]
 [4 7]]


In [4]:
print("A*B = ")
print(matrix_multiplication(A,B))

A*B = 
[[12. 62.]
 [ 8. 81.]]


In [5]:
# Check to see if my function matches numpy 
np.array_equal(np.matmul(A,B), matrix_multiplication(A,B))

True